apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ecr-refresh
resources:
  - manifests/configmap.yml
  - manifests/cronjob.yml
  - manifests/secret.yml
  - manifests/serviceaccount.yml
