apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJudWxsIiwicGFzc3dvcmQiOiJudWxsIiwiYXV0aCI6ImJuVnNiRHB1ZFd4cyJ9fX0=
kind: Secret
metadata:
  name: ecr-creds
type: kubernetes.io/dockerconfigjson
