apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-ecr-refresh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresh-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["ecr-creds"]
    verbs: ["get","delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: svc-ecr-refresh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-refresh-role
subjects:
  - kind: ServiceAccount
    name: svc-ecr-refresh
