name: Push Image
on:
  push:
    branches:
      - main
    paths:
      - '**.go'

jobs:
  build-and-push-image:
    name: Build & Push Image
    runs-on:
      - ubuntu-18.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32 # v1

      - name: Login to ECR
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build, tag, and push image to ECR
        uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547 # v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            public.ecr.aws/m3i7d4x6/ecr-refresh:latest
