name: CI
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/**.yml'

jobs:
  unit-tests:
    name: Unit Test
    runs-on:
      - ubuntu-18.04

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: '^1.15.0'

      - run: go test -cover -v ./...
